Task3 is done (for checking)
Blissfulman/Netology-homeworks pull request #3
Opened 2020-09-15 17:59 UTC by Blissfulman

2020-09-16 11:06 UTC, nskazakov requested changes

2020-09-16 11:06 UTC, nskazakov commented on Multithreading/Task3/Week3TestWork/Code/ViewController.swift
> +class BruteForceOperation: Operation {
в отдельный файл

2020-09-16 11:06 UTC, nskazakov commented on Multithreading/Task3/Week3TestWork/Code/ViewController.swift
> +            let endString = String(endChar + endChar + endChar + endChar)
Если честно, то не совсем понял подход. На лекции расскажешь:)

2020-09-20 04:54 UTC, nskazakov approved these changes

2020-09-28 05:54 UTC, closed without merging

2020-09-28 05:55 UTC, Blissfulman commented
Recommendations are made