Intermediate checking my coursework
Blissfulman/Netology-homeworks pull request #4
Opened 2020-09-28 05:51 UTC by Blissfulman

2020-10-06 07:06 UTC, nskazakov requested changes

2020-10-06 07:06 UTC, nskazakov commented on Multithreading/Course work/Course3FinalTask/Code/BlockView.swift
> +    var parentView = UIView()
мб тут private?

2020-10-06 07:06 UTC, nskazakov commented on Multithreading/Course work/Course3FinalTask/Code/BlockView.swift
> +        self.isHidden = false
тут можно брать self, где это не нужно

2020-10-06 07:06 UTC, nskazakov commented on Multithreading/Course work/Course3FinalTask/Code/BlockView.swift
> +    var parentView = UIView()
ты все равно эту вьюху в инит передаешь

2020-10-06 07:06 UTC, nskazakov commented on Multithreading/Course work/Course3FinalTask/Code/Feed/FeedTableViewCell.swift
> +                complition(post)
completion*

2020-10-06 07:06 UTC, nskazakov commented on Multithreading/Course work/Course3FinalTask/Code/Feed/FeedTableViewCell.swift
> +                complition(post)
в методах ниже такая же опечатка

2020-10-06 07:06 UTC, nskazakov commented on Multithreading/Course work/Course3FinalTask/Code/Feed/FeedTableViewCell.swift
> +}
достаточно много строк для класса. Можно разбить на экстеншины с логически связанными методами. Например, конфигурация тапов, конфигурация вью и тд. Это повысит читабельность
+ Используй // MARK: - Описание
Это для разделения логических блоков кода

2020-10-06 07:06 UTC, nskazakov commented on Multithreading/Course work/Course3FinalTask/Code/Filters/FiltersViewController.swift
> +        filtersCollectionView.register(UINib(nibName: "FiltersCollectionViewCell",
Всякие строки и цифры можно разбить на enum'ы с константами. Чтобы в коде не было строк и непонятных безымянных цифр

2020-10-06 07:06 UTC, nskazakov commented on Multithreading/Course work/Course3FinalTask/Code/Profile/HeaderProfileCollectionView.swift
> +protocol HeaderProfileCollectionViewDelegate: AnyObject {
Почему AnyObject?

2020-10-07 13:15 UTC, Blissfulman commented on Multithreading/Course work/Course3FinalTask/Code/Profile/HeaderProfileCollectionView.swift
> +protocol HeaderProfileCollectionViewDelegate: AnyObject {
Я изначально прописывал конкретный вью контроллер, но когда Максим Абакумов проверял в прошлый раз, он мне сказал не ограничивать. Типа, возможно, в будущем захочу подписать под протокол что-то ещё. И я исправил на AnyObject. А можно наверно ещё написать UIViewController.

2020-10-07 13:16 UTC, Blissfulman commented on Multithreading/Course work/Course3FinalTask/Code/BlockView.swift
> +        self.isHidden = false
Ага, убрал)

2020-10-09 20:09 UTC, Blissfulman commented
Recommendations were accepted

2020-10-13 04:25 UTC, nskazakov requested changes
- [ ] Исправить захват селф в нескольких замыканиях

2020-10-13 04:25 UTC, nskazakov commented on Multithreading/Course work/Course3FinalTask/Code/Filters/FiltersViewController.swift
> +        filtersCollectionView.register(UINib(nibName: "FiltersCollectionViewCell",
Не стал выносить?

2020-10-13 04:25 UTC, nskazakov commented on Multithreading/Course work/Course3FinalTask/Code/Filters/FiltersViewController.swift
> +            filterOperation.completionBlock = {
надо делать захват в первом замыкании
Иначе, первое замыкание у тебя захватывает селф жесткой ссылкой, а во втором ты из захваченной ссылки делаешь слабую
Но при уничтожении контроллера первое замыкание все равно будет держать твой селф))

2020-10-13 04:25 UTC, nskazakov commented on Multithreading/Course work/Course3FinalTask/Code/Filters/FiltersViewController.swift
> +        filterOperation.completionBlock = {
аналогичная ситуация, как и в прошлом комменте

2020-10-13 04:25 UTC, nskazakov commented on Multithreading/Course work/Course3FinalTask/Code/Profile/ProfileViewController.swift
> +        queue.async {
тут будет захвачено селф

2020-10-13 04:25 UTC, nskazakov commented on Multithreading/Course work/Course3FinalTask/Code/Profile/ProfileViewController.swift
> +        queue.async {
и тут

2020-10-13 05:13 UTC, Blissfulman commented on Multithreading/Course work/Course3FinalTask/Code/Filters/FiltersViewController.swift
> +        filtersCollectionView.register(UINib(nibName: "FiltersCollectionViewCell",
Что выносить? Не совсем понял. Если про константные значения, то я их сделал отдельными свойствами.

2020-10-14 09:01 UTC, nskazakov approved these changes

2020-10-14 09:06 UTC, Blissfulman commented
Changes approved

2020-10-14 09:06 UTC, closed without merging